---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: prod
  lables:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      lables:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nimeh/nginx:v0.1.0
          ports:
            - containerPort: 80